### PR TITLE
improve pipeline support for function-cidr

### LINKED ISSUE #32: Issue with using function-cidr in a pipeline
I tried to use this function in a minimalistic pipeline using the following snippet (metadata removed):

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  mode: Pipeline
  pipeline:
    # https://github.com/upbound/function-cidr/blob/main/package/input/cidr.fn.crossplane.io_parameters.yaml
    # https://github.com/upbound/function-cidr/blob/main/apis/composition.yaml
    - step: cidr-subnets
      functionRef:
        name: function-cidr
      input:
        apiVersion: cidr.fn.crossplane.io/v1beta1
        kind: Parameters
        cidrFunc: cidrsubnets
        prefix: 10.0.0.0/20
        newBits:
          - 1
          - 1
    - step: ready
      functionRef:
        name: function-auto-ready
```

However I get the following error:
```
    message: 'cannot compose resources: pipeline step "cidr-subnets" returned a fatal result: invalid Function input: parameters: Required value: cidrFunc is required'
```

When I run the examples in the repo locally using `make render` it works fine with Docker.

I'm using version `v0.4.0` of function-cidr with crossplane `v1.15.2-up.1`.

Do you have any idea what is going wrong here?

### PR DESCRIPTION
**Pull request by anessi**
### Description of your changes

Motivation: the current code does not allow to use multiple function calls in a pipeline, because it only allows to read from `observed.composite.resource` properties. In pipelines we need to be able to read values from other fields and use them as input value (e.g. `prefix`).

This PR implements these main changes:
* add possibility to set fully qualified field references (e.g. `desired.composite.resource.`, `observed.composite.resource.` or `context`)
* add consistent field support for `cidrFunc` (this is a breaking change, but used for consistency reasons: use `cidrFuncField` instead of `cidrFunc` now)
* add output field

Please see the added example pipeline for a concrete example how I use the function of the use-case.

Fixes #32

The updated function is available for testing as:

```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-cidr
spec:
  package: xpkg.upbound.io/anessi/function-cidr:v0.5.4
```

Please note that I'm not a GO developer, so review the code carefully as I might have missed some obvious things 😃 

I have:
- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).

### CODE REVIEW

**Comment by humoflife** [comment]
Do you need the backslashes in. apis/composition-pipeline-context.yaml here: `prefixField: context.apiextensions\.crossplane\.io/extra-resources.XCluster.0.spec.cidrBlock` ? If not, please remove them.

**Comment by humoflife** [comment]
Rendering cidrsubnetloop and cidrsubnets stopped working. Please take a look.

```
Rendering examples/xr-cidrsubnetloop.yaml...
crossplane: error: cannot render composite resource: pipeline step "cidr" returned a fatal result: cannot get output from field spec.parameters.output for XCIDR: spec.parameters.output: no such field
Rendering examples/xr-cidrsubnets.yaml...
crossplane: error: cannot render composite resource: pipeline step "cidr" returned a fatal result: cannot get output from field spec.parameters.output for XCIDR: spec.parameters.output: no such field
make: *** [render] Error 1
```

**Comment by humoflife** [comment]
`function-cidr` is offering `cidrFunc` and `cidrFuncField` inputs.

- `cidrFunc` allows direct specification of the desired CIDR function.
- `cidrFuncField` allows specification of the field where the CIDR function name is specified, e.g. `cidrhost`.

The description of the changes includes:

... add consistent field support for cidrFunc (this is a breaking change, but used for consistency reasons: use cidrFuncField instead of cidrFunc now)

What is the breaking change and why should not both `cidrFunc` and `cidrFuncField` be supported with their original intent and in analogy to other parameters?

**Comment by humoflife** [comment]
Please add test coverage in `fn_test.go`.

**Comment by humoflife** [comment]
Was the `output` field not supported prior to this PR? What was added?

**Comment by humoflife** [comment]
Please run all yaml files through yamlfmt (https://formulae.brew.sh/formula/yamlfmt if you are using Mac OSX) to update the indentation of arrays or manually update, e.g.

```
foo:
  - bar1
  - bar2
``` 

 versus:
 
 ```
 foo:
 - bar1
 - bae2
```

**Comment by humoflife** [comment]
In the comment in input/v1beta1/parameters.go, please replace

```
// cidrfunc is one of cidrhost, cidrnetmast, cidesubnet, cidrsubnets, cidrsubnetloop
```

with

```
// cidrfunc is one of cidrhost, cidrnetmast, cidrsubnet, cidrsubnets, cidrsubnetloop
```

**Comment by anessi** [comment]
> Do you need the backslashes in. apis/composition-pipeline-context.yaml here: `prefixField: context.apiextensions\.crossplane\.io/extra-resources.XCluster.0.spec.cidrBlock` ? If not, please remove them.

They are needed because it's a key with dots in the name (`apiextensions.crossplane.io/extra-resources`). See https://github.com/crossplane-contrib/function-extra-resources/tree/main

> make render
This is fixed now. Thanks for noticing.

> cidrFuncField vs cidrFunc
There was no `cidrFuncField` before, but instead `cidrFunc` had the same behavior as now `cidrFuncField`. This was inconsistent and I fixed this to make it consistent. See https://github.com/upbound/function-cidr/pull/33/files#diff-e7b8a7f13b611cc9ad80aad4c3c35c12930ad31ddfb43b721a692c0c8d069391

> outputField vs output
`output` was not supported, but only `outputField`

> yamlfmt
The files are formatted with `yamlfmt` now.

> // cidrfunc is one of cidrhost, cidrnetmast, cidrsubnet, cidrsubnets, cidrsubnetloop
Fixed the comments. There was a second spelling mistake (cidrnetmast).

> Please add test coverage in fn_test.go.
Looks like the project does not have any tests so far. What would you like me to do?

Wouldn't it be easier if you add the comments directly on the code instead of different comments here? Makes it a bit hard to give replies to individual comments.

**Comment by haarchri** [comment]
@anessi sorry for late Response - can you rebase your PR?

**Comment by anessi** [comment]
@haarchri : I have update the code accordingly. It got a bit simpler due to the improvements implemented in https://github.com/upbound/function-cidr/commit/08009240023622f8b3f52cbf0a07366d71ec0ff3

I also added 2 tests.

**Review by haarchri — APPROVED** [review]

**Pull request merged**
